### PR TITLE
App links feature

### PR DESCRIPTION
**Pull request by saperi22**
### Summary of changes

 - Merge app links feature into main

### Checklist

 - [x] Added a changelog entry
 - [x] Relevant test coverage

### CODE REVIEW

**Review by tdchow — APPROVED** [review]

**Comment by saperi22** [comment]
@tdchow any opinions on size of test classes? Detekt is failing on `BraintreeClientUnitTest` for large class.

**Comment by tdchow** [comment]
> @tdchow any opinions on size of test classes? Detekt is failing on `BraintreeClientUnitTest` for large class.

Maybe we can add a suppress annotation for the test class and create a ticket to refactor it post-release.

**Review by sshropshire — APPROVED** [review]

**Review by jaxdesmarais — APPROVED** [review]

**Comment by jaxdesmarais** [comment]
> Maybe we can add a suppress annotation for the test class and create a ticket to refactor it post-release. Also open to updating the detekt ruleset if folks would rather do that.

I would be fine suppressing it for the test class or updating the rule

**Comment by tdchow** [comment]
On second thought, maybe we update the rule for test classes.

**Pull request merged**
