### PR TITLE
Add checking to paypal deeplink support

### PR DESCRIPTION
**Pull request by ayer-ribeiro**
### Summary of changes

 - Converted AppHelper class to Kotlin
 - Removed unnecessary nullability checks in AppHelper
 - Removed AppHelper hardcoded flags
 - Added isDeepLinkSupportedByPayPalApp function to DeviceInspector
 - Changed usage of isPayPalAppInstalled to isDeepLinkSupportedByPayPalApp is PayPal client logic
 - Added Check if PayPal app app links are verified before get PayPalPaymentResource to avoid to get an app switch redirect url if PayPal app isn't installed
 - Added a retry without app switch flag in post request used to obtain the PayPalPaymentResource when the merchant enable app switch and user has an old PayPal version

### Checklist

 - [x] Added a changelog entry
 - [x] Relevant test coverage

### Authors

- @ayer-ribeiro

### CODE REVIEW

**Comment by sarahkoop** [comment]
Hi @ayer-ribeiro Thanks for submitting this contribution! Were you experiencing an error without these changes? Could you provide more details about that if that is the case?

**Comment by ayer-ribeiro** [comment]
Hi @sarahkoop 
Checking if the device supports the intent instead of checking if the PayPal app avoids to handle the billing flow as app switch if there is PayPal version installed on device that doesn't supports App Switch

**Comment by ayer-ribeiro** [comment]
@sarahkoop 
just added a new commit to check if PayPal app is installed before tries to get configuration avoiding get an app switch redirect url.
With this check the braintree sdk properly open the correct approval url instead of open an app switch url that causes an error.

**Comment by ayer-ribeiro** [comment]
@sarahkoop the last commit is avoiding to start the app switch flow it the PayPal app doesn't have verified the app links yet.

**Comment by ayer-ribeiro** [comment]
@sarahkoop I added in the last commit a check to avoid an error when the merchant enable app switch and user has an old PayPal version by requesting again the PayPalPaymentResource without the app switch flag.

**Comment by ayer-ribeiro** [comment]
## Cases where PayPal app can't handle the app switch link:
- App links not verified yet
- PayPal app in older versions

### Flow before
```mermaid
sequenceDiagram
    participant MerchantApp
    participant PayPalClient
    participant PayPalInternalClient
    participant BraintreeClient
    participant Redirect
    MerchantApp->>PayPalClient: createPaymentAuthRequest
    PayPalClient->>BraintreeClient: getConfiguration
    BraintreeClient-->>PayPalClient: Callback
    PayPalClient->>PayPalClient: sendPayPalRequest 
    PayPalClient->>PayPalInternalClient: sendRequest
    PayPalInternalClient->>BraintreeClient: getConfiguration
    BraintreeClient-->>PayPalInternalClient: Callback
    Note right of PayPalInternalClient: If PayPal app ins't installed <br/>set enablePayPalAppSwitch as false 
    PayPalInternalClient->>PayPalInternalClient: sendPost
    PayPalInternalClient->>BraintreeClient: sendPost
    BraintreeClient-->>PayPalInternalClient: Callback with redirect url
    BraintreeClient->>Redirect: Redirect to chrome with app switch url and show error
```

### Flow after:
```mermaid
sequenceDiagram
    participant MerchantApp
    participant PayPalClient
    participant PayPalInternalClient
    participant BraintreeClient
    participant Redirect
    MerchantApp->>PayPalClient: createPaymentAuthRequest
    PayPalClient->>BraintreeClient: getConfiguration
    BraintreeClient-->>PayPalClient: Callback
    PayPalClient->>PayPalClient: sendPayPalRequest 
    Note right of PayPalClient: If PayPal app links are not verified yet <br/>set enablePayPalAppSwitch as false 
    PayPalClient->>PayPalInternalClient: sendRequest
    PayPalInternalClient->>BraintreeClient: getConfiguration
    BraintreeClient-->>PayPalInternalClient: Callback
    PayPalInternalClient->>PayPalInternalClient: sendPost
    PayPalInternalClient->>BraintreeClient: sendPost
    BraintreeClient-->>PayPalInternalClient: Callback with redirect url
    Note right of PayPalInternalClient: If PayPal can't handle the redirect link <br/>calls onPayPalAppDeepLinkNotAvailable 
    PayPalInternalClient->>PayPalInternalClient: onPayPalAppDeepLinkNotAvailable
    PayPalInternalClient->>PayPalInternalClient: sendPost
    PayPalInternalClient->>BraintreeClient: sendPost
    BraintreeClient-->>PayPalInternalClient: Callback with redirect new url
    BraintreeClient->>Redirect: Redirect to chrome with non app switch url
```

**Comment by ayer-ribeiro** [comment]
The errors only occur in sandbox, it seems that server-side handling avoids these errors in production.
I'm closing this PR, as this is not a production bug and the ideal solution for sandbox errors is to handle them on the server side as in production.

**Pull request closed without merging**
