### PR TITLE
Update Google Wallet dependency

### LINKED ISSUE #446: Google Pay - Update Wallet Version
### General information

* SDK/Library version: 4.5.0
* Environment: Both
* Android Version and Device: All
* Braintree dependencies:
```
  com.braintreepayments.api:paypal
  com.braintreepayments.api:google-pay
  com.braintreepayments.api:card
```

### Issue description

I am working through the 3.x migration to 4.x and was wondering why we are required to use such an old version of Google wallet library? The latest version is com.google.android.gms:play-services-wallet:18.1.3 and you have it set for [16.0.1](https://github.com/braintree/braintree_android/blob/master/GooglePay/build.gradle#L38)

### PR DESCRIPTION
**Pull request by nate-eisner**
### Summary of changes

 - Version bump of `com.google.android.gms:play-services-wallet`
 - Fixes #446 

 ### Checklist

 - [x] Added a changelog entry

- @nate-eisner

### CODE REVIEW

**Comment by sarahkoop** [comment]
Hi @nate-eisner thanks for opening this PR, we'd need the unit tests to be passing to approve it. You can run them locally while developing using `rake unit_tests`

**Comment by nate-eisner** [comment]
> Hi @nate-eisner thanks for opening this PR, we'd need the unit tests to be passing to approve it. You can run them locally while developing using `rake unit_tests`

:wave: @sarahkoop   It looks like the new wallet version is conflicting with `PowerMock` and the way it mocks static classes. I am not a big fan of `PowerMock` for this reason :cry: 

Is anyone against me doing some refactoring of these tests and wrapping the static `Wallet` class so we don't have to use PowerMock here?

**Comment by sarahkoop** [comment]
> Is anyone against me doing some refactoring of these tests and wrapping the static `Wallet` class so we don't have to use PowerMock here?

@nate-eisner We are open to you refactoring the tests - we've had issues with PowerMock and static classes in the past as well.

**Comment by sarahkoop** [comment]
This change was released in `4.8.1`. Closing this PR as redundant.

**Pull request closed without merging**
