### PR TITLE
Fix memory issue with DataCollector class

### PR DESCRIPTION
**Pull request by KunJeongPark**
### Summary of changes

 - fix memory leak in "DataCollector" 

- @KunJeongPark 
- @sshropshire

### CODE REVIEW

**Review by jaxdesmarais — COMMENTED** [review]
Is this the same as #703? Also do we want to have the full URL links to our internal Jira on public GitHub?

**Comment by KunJeongPark** [comment]
thanks Jax for the catch. I deleted the reference to the live issue. This is not the same, I just wanted to add the memory leak fix that we worked on together on DataCollector. I didn't mean to include previous changes.

**Comment by jaxdesmarais** [comment]
> thanks Jax for the catch. I deleted the reference to the live issue. This is not the same, I just wanted to add the memory leak fix that we worked on together on DataCollector. I didn't mean to include previous changes.

Gotcha - yeah a little confusing to see the `BraintreeClient.kt` changes in both PRs as it's not clear immediately what is being changed (I see the diff in `DataCollector.java` now). If you merge `fix_browser_switch_crash` into `dataCollectorMemoryLeak` it should remove the diff from this PR to make it clearer!

**Comment by scannillo** [comment]
Can you explain a little about what issue this PR fixes exactly?

**Comment by sshropshire** [comment]
> Can you explain a little about what issue this PR fixes exactly?

There's potential for a leak of an `Activity` reference within `DataCollector`. This PR grabs an `applicationContext` reference immediately to retain in the data collector callback. Originally, the callback was retaining the context passed in by the merchant, which is likely to be an `Activity`. Leaking activities in Android is pretty much the ultimate deal breaker because they tend to take up a lot of memory.

**Review by jaxdesmarais — APPROVED** [review]

**Pull request merged**
