### PR TITLE
Defer adding SamsungPay to CHANGELOG

### PR DESCRIPTION
**Pull request by sshropshire**
### Summary of changes

 - Defer adding SamsungPay to CHANGELOG until it can be properly tested.

 ### Checklist

 - [x] ~Added~ Removed a changelog entry

### Authors

- @sshropshire

### CODE REVIEW

**Review by sarahkoop — APPROVED** [review]

**Comment by scannillo** [comment]
Shouldn't we also remove the actual SamsungPay code as well as the CHANGELOG entry?

**Comment by sshropshire** [comment]
> Shouldn't we also remove the actual SamsungPay code as well as the CHANGELOG entry?

I think keeping the code will make it easier to release SamsungPay once we're able to verify it working. We technically won't be releasing it until we add the module to our `Rakefile`. It's almost like a `package-private` module now.

**Comment by scannillo** [comment]
> I think keeping the code will make it easier to release SamsungPay once we're able to verify it working. We technically won't be releasing it until we add the module to our Rakefile. It's almost like a package-private module now.

Gotcha, so merchants can't access it in it's current state then? This is good to know!

**Comment by sshropshire** [comment]
> Gotcha, so merchants can't access it in it's current state then? This is good to know!

Yup! The SamsungPay artifact won't get published to Sonatype until we explicitly add it to our release script.

**Pull request merged**
