### PR TITLE
Method on braintree client for invalidating cached auth

### LINKED ISSUE #544: No ability to invalidate cached credentials
### General information

* SDK/Library version: 4.9.0
* Environment: Production
* Android Version and Device: N/A
* Braintree dependencies:

com.braintreepayments.api:card:4.9.0
com.braintreepayments.api:data-collector:4.9.0
com.braintreepayments.api:google-pay:4.9.0
com.braintreepayments.api:paypal:4.9.0
com.braintreepayments.api:three-d-secure:4.9.0
com.braintreepayments.api:venmo:4.9.0

### Issue description

There is currently no way to invalidate the credentials once they are read once from a `ClientTokenProvider` or set via `initialAuthString`. Because of the instantiation strategy for 3rd party clients (google pay, venmo, etc.) on android requiring the instantiation to be prior to the onCreate lifecycle, there is no way to change the braintree client or invalidate the cached credentials once a token has been read.

We have a few places where we are being provided a braintree client token to use for authentication, and the permissions tied to that token may vary from screen to screen. Because we use a single activity application, the clients are shared across all screens. Once the authentication token is read once (either from the `initialAuthString` or `clientTokenProvider`), that authentication value persists for the entirety of the application. This behavior has downstream effects for us if, for example, 3D Secure is not enabled for the first token received, but is for a subsequent token. 

From the contract of the `ClientTokenProvider`, it appears from the onset that this will act like an interceptor and will read the client token value any time authorization is requested. Instead, the `ClientTokenProvider` class is essentially setting the `initialAuthString` in a `by lazy` way.

There are several solutions to this, which I'd be happy to make a PR for, but I'm not sure what is preferable. One of the main problems from an architecture perspective is that external consumers of the braintree api don't have any concept of the `AuthorizationLoader` or its caching strategy.

This is our interim solution, which uses reflection and is very undesirable:

```
private fun forceAuthorizationRefresh() = try {
        // Find the authorization loader field that has the cached auth credentials
        val authorizationLoaderField = braintreeClient.javaClass
            .getDeclaredField("authorizationLoader")
            .apply {
                isAccessible = true
            }

        val authorizationField = authorizationLoaderField
            .type
            .getDeclaredField("authorization")

        // Get the current value of the authorizationLoader field so that we can overwrite it
        val authorizationLoader = authorizationLoaderField.get(braintreeClient)

        authorizationField
            .apply {
                isAccessible = true
                // Actually apply the nullification here so the credential is refetched on next getAuthorization request
                set(authorizationLoader, null)
            }
    } catch (e: Exception) {
        e.printStackTrace()
    }
```

I think the most straightforward solution to this would be to add a method to the interface for `ClientTokenProvider` along the lines of a `boolean fetchNewToken()` (name pending!) and is then used in the `AuthorizationLoader` code as such:

```
void loadAuthorization(@NonNull final AuthorizationCallback callback) {
        final boolean shouldForceClientTokenProviderUsage = clientTokenProvider != null && clientTokenProvider.fetchNewToken(); 
        if (authorization != null && !shouldForceClientTokenProviderUsage) {
            callback.onAuthorizationResult(authorization, null);
        } else if (clientTokenProvider != null) {
            clientTokenProvider.getClientToken(new ClientTokenCallback() {
                @Override
                public void onSuccess(@NonNull String clientToken) {
                    authorization = Authorization.fromString(clientToken);
                    callback.onAuthorizationResult(authorization, null);
                }

                @Override
                public void onFailure(@NonNull Exception error) {
                    callback.onAuthorizationResult(null, error);
                }
            });
        } else {
            String clientSDKSetupURL
                = "https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/android/v4#initialization";
            String message = String.format("Authorization required. See %s for more info.", clientSDKSetupURL);
            callback.onAuthorizationResult(null, new BraintreeException(message));
        }
    }
```

Another option would be to just never use the cached value of `authorization` if `clientTokenProvider` is non-null, but that is probably a breaking change.

If the `BraintreeClient` could be swapped for the 3rd party clients, that is also an option (albeit more dangerous since there are so many touchpoints for those variables).

A final option is probably to expose a method / param on the braintree client that disables the cached authentication.

### PR DESCRIPTION
**Pull request by josephyanks**
Thank you for your contribution to Braintree. 

> Before submitting this PR, note that we cannot accept language translation PRs. We support the same languages that are supported by PayPal, and have a dedicated localization team to provide the translations. If there is an error in a specific translation, you may open an issue and we will escalate it to the localization team.

Resolves #544 

I think that this is the most straightforward solution, although it involves adding a method onto the `BraintreeClient`, rather than in the `ClientTokenProvider`. There is another option that adds a `shouldUseCachedToken` method to the `ClientTokenProvider` seen in this PR: #546

I'll add tests and a changelog entry if / when we decide between the two PR's

### Summary of changes

 - Adds method `invalidateClientToken` on `BraintreeClient` that will invalidate the cached authorization credentials for the next `loadAuthorization`. Note that we can only invalidate this valid if a `ClientTokenProvider` was provided.

 ### Checklist

 - [x] Added a changelog entry

- @josephyanks

### CODE REVIEW

**Comment by sshropshire** [comment]
@josephyanks this is awesome! Thanks for taking the time to contribute 🙏

I have a few thoughts:
1. I like the idea of having an `invalidateClientToken()` method on `BraintreeClient` – it's the public-facing entry point of the SDK created by the merchant. Allowing merchants to clear the Client Token cache feels like a good feature to add.
2. I think we can remove the `invalidateNextAuthorizationRequest` boolean flag in favor of setting the [authorization property](https://github.com/braintree/braintree_android/blob/c4bf27878725edaff705617ac6a617f98530cf8a/BraintreeCore/src/main/java/com/braintreepayments/api/AuthorizationLoader.java#L8) to `null`. `AuthorizationLoader` has logic in place to [re-fetch a client token](https://github.com/braintree/braintree_android/blob/c4bf27878725edaff705617ac6a617f98530cf8a/BraintreeCore/src/main/java/com/braintreepayments/api/AuthorizationLoader.java#L22) when needed.

**Comment by josephyanks** [comment]
Just two follow up questions and I'll update the PR.

1. The reason I made the `invalidateNextAuthorizationRequest` was in case we crashed before the next `loadAuthorization` call. I see that braintree will pull the last known authorization object out for logging in the case of a crash. Do we want to create a second authorization field that retains the last authorization value (and ignores clears)?
2. I still think that we need to check for the presence of the `clientTokenProvider`, otherwise if we allow the `invalidateClientToken` to null out the `authorization` field, and the `clientTokenProvider` is null, then the next requests will fail. That hidden implementation detail is the cause of this reported issue in the first place. From the `AuthorizationLoader` code, it looks like it takes both the initial value as well as the `clientTokenProvider` and uses both but, in reality, it's only using one. If this was rewritten in Kotlin, I'd assume these two variables would be replaced with a `sealed class`, where the hardcoded value and `clientTokenProvider` are two implementations. Let me know if you think we should still be nulling out the `authorization` value if there is a null `clientTokenProvider`

**Comment by sshropshire** [comment]
Oh I understand. I wouldn't worry about that particular edge case since the crash log will be uploaded when the app is relaunched. And as a backup, Google Play has its own crash analytics available for merchants to use when diagnosing production issues.

For No. 2, that is a good point. We would only want to clear the cache for `ClientTokenProvider` integrations. That's a good piece of acceptance criteria for this use case. We can mention in the docs that the `invalidateClientToken()` method does nothing otherwise.

**Comment by josephyanks** [comment]
Updated, let me know what else is required. Thanks!

**Comment by sshropshire** [comment]
> Updated, let me know what else is required. Thanks!

Looks great! I have a couple updates [we can add](https://github.com/josephyanks/braintree_android/pull/1), then I think it'll be good for a formal review by the SDK team.

**Comment by josephyanks** [comment]
Just merged them into my branch, thank you

**Review by sarahkoop — APPROVED** [review]
Looks good to me!

**Comment by josephyanks** [comment]
Merged the conflicting `CHANGELOG.md`

**Review by sshropshire — APPROVED** [review]
:fire:

**Comment by josephyanks** [comment]
Thank you all! @sshropshire do you have an idea of when the next release is schedule for? We'd love to take out the reflection nullification hack from our codebase :)

**Pull request merged**
