### PR TITLE
Bundle Cardinal aar from Filesystem

### PR DESCRIPTION
**Pull request by sarahkoop**
### Summary of changes

 -  Remove Bintray dependency for Cardinal SDK

 ### Checklist

 - [x] Added a changelog entry

- @sshropshire 
- @sarahkoop

### CODE REVIEW

**Comment by sestevens** [comment]
I like it. We should probably also add a note about this to the migration guide.

**Comment by sarahkoop** [comment]
> I like it. We should probably also add a note about this to the migration guide.

Good call, we added a note that these credentials can be removed.  We are also planning to make this change in a `v3` release, but still think it's noteworthy to include in the migration guide.

**Review by scannillo — APPROVED** [review]

**Comment by scannillo** [comment]
Might be helpful if CHANGELOG refers to the GH issue #

**Comment by sarahkoop** [comment]
We are reverting this in v3, since local repository does not propagate MPI aar file. Closing this PR.

**Pull request closed without merging**
